// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: meals.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (name, price, img_url)
VALUES ($1, $2, $3)
RETURNING meal_id, name, img_url, price, available, created_at, modified_at
`

type CreateMealParams struct {
	Name   string
	Price  decimal.Decimal
	ImgUrl string
}

type CreateMealRow struct {
	MealID     uuid.UUID
	Name       string
	ImgUrl     string
	Price      decimal.Decimal
	Available  sql.NullBool
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (CreateMealRow, error) {
	row := q.db.QueryRow(ctx, createMeal, arg.Name, arg.Price, arg.ImgUrl)
	var i CreateMealRow
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.ImgUrl,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE meal_id = $1
`

func (q *Queries) DeleteMeal(ctx context.Context, mealID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeal, mealID)
	return err
}

const getAllMeals = `-- name: GetAllMeals :many
SELECT meal_id, name, img_url, price, available, created_at, modified_at
FROM meals
`

type GetAllMealsRow struct {
	MealID     uuid.UUID
	Name       string
	ImgUrl     string
	Price      decimal.Decimal
	Available  sql.NullBool
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

func (q *Queries) GetAllMeals(ctx context.Context) ([]GetAllMealsRow, error) {
	rows, err := q.db.Query(ctx, getAllMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMealsRow
	for rows.Next() {
		var i GetAllMealsRow
		if err := rows.Scan(
			&i.MealID,
			&i.Name,
			&i.ImgUrl,
			&i.Price,
			&i.Available,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealByID = `-- name: GetMealByID :one
SELECT meal_id, name, img_url, price, available, created_at, modified_at
FROM meals
WHERE meal_id = $1
`

type GetMealByIDRow struct {
	MealID     uuid.UUID
	Name       string
	ImgUrl     string
	Price      decimal.Decimal
	Available  sql.NullBool
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

func (q *Queries) GetMealByID(ctx context.Context, mealID uuid.UUID) (GetMealByIDRow, error) {
	row := q.db.QueryRow(ctx, getMealByID, mealID)
	var i GetMealByIDRow
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.ImgUrl,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getMealByName = `-- name: GetMealByName :one
SELECT meal_id, name, img_url, price, available, created_at, modified_at
FROM meals
WHERE name = $1
`

type GetMealByNameRow struct {
	MealID     uuid.UUID
	Name       string
	ImgUrl     string
	Price      decimal.Decimal
	Available  sql.NullBool
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

func (q *Queries) GetMealByName(ctx context.Context, name string) (GetMealByNameRow, error) {
	row := q.db.QueryRow(ctx, getMealByName, name)
	var i GetMealByNameRow
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.ImgUrl,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const searchMeal = `-- name: SearchMeal :many
SELECT meal_id, name, price, available, created_at, modified_at, img_url FROM meals WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) SearchMeal(ctx context.Context, dollar_1 sql.NullString) ([]Meal, error) {
	rows, err := q.db.Query(ctx, searchMeal, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.MealID,
			&i.Name,
			&i.Price,
			&i.Available,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.ImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET
    name = COALESCE($2, name),
    img_url = COALESCE($3, img_url),
    price = COALESCE($4, price),
    available = COALESCE($5, available),
    modified_at = now()
WHERE meal_id = $1
RETURNING meal_id, name, img_url, price, available, created_at, modified_at
`

type UpdateMealParams struct {
	MealID    uuid.UUID
	Name      sql.NullString
	ImgUrl    sql.NullString
	Price     decimal.NullDecimal
	Available sql.NullBool
}

type UpdateMealRow struct {
	MealID     uuid.UUID
	Name       string
	ImgUrl     string
	Price      decimal.Decimal
	Available  sql.NullBool
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (UpdateMealRow, error) {
	row := q.db.QueryRow(ctx, updateMeal,
		arg.MealID,
		arg.Name,
		arg.ImgUrl,
		arg.Price,
		arg.Available,
	)
	var i UpdateMealRow
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.ImgUrl,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
