// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: meals.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (name, price, quantity)
VALUES ($1, $2, $3)
RETURNING meal_id, name, price, available, created_at, quantity, modified_at
`

type CreateMealParams struct {
	Name     string
	Price    decimal.Decimal
	Quantity int32
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal, arg.Name, arg.Price, arg.Quantity)
	var i Meal
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.Quantity,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE meal_id = $1
`

func (q *Queries) DeleteMeal(ctx context.Context, mealID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeal, mealID)
	return err
}

const getAllMeals = `-- name: GetAllMeals :many
SELECT meal_id, name, price, available, created_at, quantity, modified_at
FROM meals
`

func (q *Queries) GetAllMeals(ctx context.Context) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getAllMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.MealID,
			&i.Name,
			&i.Price,
			&i.Available,
			&i.CreatedAt,
			&i.Quantity,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealByID = `-- name: GetMealByID :one
SELECT meal_id, name, price, available, created_at, quantity, modified_at
FROM meals
WHERE meal_id = $1
`

func (q *Queries) GetMealByID(ctx context.Context, mealID uuid.UUID) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealByID, mealID)
	var i Meal
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.Quantity,
		&i.ModifiedAt,
	)
	return i, err
}

const getMealByName = `-- name: GetMealByName :one
SELECT meal_id, name, price, available, created_at, quantity, modified_at
FROM meals
WHERE name = $1
`

func (q *Queries) GetMealByName(ctx context.Context, name string) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealByName, name)
	var i Meal
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.Quantity,
		&i.ModifiedAt,
	)
	return i, err
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET
    name = COALESCE($2, name),
    price = COALESCE($3, price),
    available = COALESCE($4, available),
    quantity = COALESCE($5, quantity),
    modified_at = now()
WHERE meal_id = $1
RETURNING meal_id, name, price, available, created_at, quantity, modified_at
`

type UpdateMealParams struct {
	MealID    uuid.UUID
	Name      sql.NullString
	Price     decimal.NullDecimal
	Available sql.NullBool
	Quantity  sql.NullInt32
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, updateMeal,
		arg.MealID,
		arg.Name,
		arg.Price,
		arg.Available,
		arg.Quantity,
	)
	var i Meal
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.Quantity,
		&i.ModifiedAt,
	)
	return i, err
}
