// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Meal struct {
	MealID    uuid.UUID
	Name      string
	Price     decimal.Decimal
	Available sql.NullBool
	CreatedAt sql.NullTime
}

type User struct {
	UserID     uuid.UUID
	Username   string
	Email      string
	Password   string
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}
