// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Meal struct {
	MealID     uuid.UUID
	Name       string
	Price      decimal.Decimal
	Available  sql.NullBool
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

type Order struct {
	OrderID     uuid.UUID
	UserID      uuid.NullUUID
	OrderStatus sql.NullString
	TotalPrice  decimal.Decimal
	CreatedAt   sql.NullTime
	ModifiedAt  sql.NullTime
}

type OrderItem struct {
	OrderItemID uuid.UUID
	OrderID     uuid.NullUUID
	MealID      uuid.NullUUID
	Quantity    sql.NullInt32
	Price       decimal.Decimal
}

type User struct {
	UserID     uuid.UUID
	Username   string
	Email      string
	Password   string
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}
