// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Meal struct {
	MealID    int32
	Name      string
	Price     decimal.Decimal
	Available sql.NullBool
	CreatedAt sql.NullTime
}

type Order struct {
	OrderID    int32
	UserID     sql.NullInt32
	TotalPrice decimal.Decimal
	Status     string
	OrderDate  sql.NullTime
}

type User struct {
	Username  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UserID    uuid.NullUUID
}
