// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_items.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, meal_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING order_item_id, order_id, meal_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID  uuid.NullUUID
	MealID   uuid.NullUUID
	Quantity sql.NullInt32
	Price    decimal.Decimal
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.MealID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.MealID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT order_item_id, order_id, meal_id, quantity, price
FROM order_items
WHERE order_item_id = $1
`

func (q *Queries) GetOrderItemByID(ctx context.Context, orderItemID uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItemByID, orderItemID)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.MealID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getOrderItemByOrderID = `-- name: GetOrderItemByOrderID :many
SELECT order_item_id, order_id, meal_id, quantity, price
FROM order_items
WHERE order_id = $1
`

func (q *Queries) GetOrderItemByOrderID(ctx context.Context, orderID uuid.NullUUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderItemID,
			&i.OrderID,
			&i.MealID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE order_items
SET 
    order_id = COALESCE($2, order_id),
    meal_id = COALESCE($3, meal_id), 
    quantity = COALESCE($4, quantity),
    price = COALESCE($5, price)
WHERE order_item_id = $1
RETURNING order_item_id, order_id, meal_id, quantity, price
`

type UpdateOrderItemParams struct {
	OrderItemID uuid.UUID
	OrderID     uuid.NullUUID
	MealID      uuid.NullUUID
	Quantity    sql.NullInt32
	Price       decimal.NullDecimal
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItem,
		arg.OrderItemID,
		arg.OrderID,
		arg.MealID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.MealID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}
