// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, order_status, total_price)
VALUES ($1, $2, $3)
RETURNING order_id, user_id, order_status, total_price, created_at, modified_at
`

type CreateOrderParams struct {
	UserID      uuid.NullUUID
	OrderStatus sql.NullString
	TotalPrice  decimal.Decimal
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.OrderStatus, arg.TotalPrice)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE order_id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, orderID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT order_id, user_id, order_status, total_price, created_at, modified_at
FROM orders
WHERE order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
	SELECT 
		o.order_id,
		o.user_id,
		o.order_status,
		o.total_price,
		o.created_at,
		o.modified_at,
		oi.order_item_id,
		oi.meal_id,
		oi.quantity,
		oi.price
	FROM orders o
	LEFT JOIN order_items oi ON o.order_id = oi.order_id
	ORDER BY o.created_at DESC
`

type ListOrdersRow struct {
	OrderID     uuid.UUID
	UserID      uuid.NullUUID
	OrderStatus sql.NullString
	TotalPrice  decimal.Decimal
	CreatedAt   sql.NullTime
	ModifiedAt  sql.NullTime
	OrderItemID uuid.NullUUID
	MealID      uuid.NullUUID
	Quantity    sql.NullInt32
	Price       decimal.NullDecimal
}

func (q *Queries) ListOrders(ctx context.Context) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.UserID,
			&i.OrderStatus,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.OrderItemID,
			&i.MealID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET 
    order_status = COALESCE($2, order_status), 
    total_price = COALESCE($3, total_price), 
    modified_at = now()
WHERE order_id = $1
RETURNING order_id, user_id, order_status, total_price, created_at, modified_at
`

type UpdateOrderParams struct {
	OrderID     uuid.UUID
	OrderStatus sql.NullString
	TotalPrice  decimal.NullDecimal
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.OrderID, arg.OrderStatus, arg.TotalPrice)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
