// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, order_status, total_price)
VALUES ($1, $2, $3)
RETURNING order_id, user_id, order_status, total_price, created_at, modified_at
`

type CreateOrderParams struct {
	UserID      uuid.NullUUID
	OrderStatus sql.NullString
	TotalPrice  decimal.Decimal
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.OrderStatus, arg.TotalPrice)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE order_id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, orderID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT order_id, user_id, order_status, total_price, created_at, modified_at
FROM orders
WHERE order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT order_id, user_id, order_status, total_price, created_at, modified_at
FROM orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.UserID,
			&i.OrderStatus,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET order_status = $2
WHERE order_id = $1
RETURNING order_id, user_id, order_status, total_price, created_at, modified_at
`

type UpdateOrderStatusParams struct {
	OrderID     uuid.UUID
	OrderStatus sql.NullString
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.OrderID, arg.OrderStatus)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
