// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order_items.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, meal_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING order_item_id, order_id, meal_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID  uuid.NullUUID
	MealID   uuid.NullUUID
	Quantity sql.NullInt32
	Price    decimal.Decimal
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.MealID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.MealID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT order_item_id, order_id, meal_id, quantity, price
FROM order_items
WHERE order_item_id = $1
`

func (q *Queries) GetOrderItemByID(ctx context.Context, orderItemID uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItemByID, orderItemID)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.MealID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}
