// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password, profile_picture)
VALUES ($1, $2, $3, $4)
RETURNING user_id, username, email, password, profile_picture, created_at, modified_at
`

type CreateUserParams struct {
	Username       string
	Email          string
	Password       string
	ProfilePicture sql.NullString
}

type CreateUserRow struct {
	UserID         uuid.UUID
	Username       string
	Email          string
	Password       string
	ProfilePicture sql.NullString
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.ProfilePicture,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, password, profile_picture, created_at, modified_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	UserID         uuid.UUID
	Username       string
	Email          string
	Password       string
	ProfilePicture sql.NullString
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, password, profile_picture, created_at, modified_at
FROM users
WHERE user_id = $1
`

type GetUserByIDRow struct {
	UserID         uuid.UUID
	Username       string
	Email          string
	Password       string
	ProfilePicture sql.NullString
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, password, profile_picture, created_at, modified_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	UserID         uuid.UUID
	Username       string
	Email          string
	Password       string
	ProfilePicture sql.NullString
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, email, password, profile_picture, created_at, modified_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	UserID         uuid.UUID
	Username       string
	Email          string
	Password       string
	ProfilePicture sql.NullString
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.ProfilePicture,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUser = `-- name: SearchUser :many
SELECT user_id, username, email, password, created_at, modified_at, profile_picture FROM users WHERE username ILIKE '%' || $1 || '%'
`

func (q *Queries) SearchUser(ctx context.Context, dollar_1 sql.NullString) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.ProfilePicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    username = COALESCE($2, username), 
    email = COALESCE($3, email), 
    password = COALESCE($4, password),
    profile_picture = COALESCE($5, profile_picture),

    modified_at = now()
WHERE user_id = $1
RETURNING user_id, username, email, password, created_at, modified_at, profile_picture
`

type UpdateUserParams struct {
	UserID         uuid.UUID
	Username       sql.NullString
	Email          sql.NullString
	Password       sql.NullString
	ProfilePicture sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.ProfilePicture,
	)
	return i, err
}
